<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="HP" failures="2" tests="2" name="Test(failed)" time="15.264" errors="0" timestamp="2025-07-06T11:23:48 AST">
  <testcase classname="testCases.TC001EnrollingTest" name="verify_eroll" time="1.499">
    <failure type="java.lang.AssertionError" message="expected [test1] but found [test]">
      <![CDATA[java.lang.AssertionError: expected [test1] but found [test]
at testCases.TC001EnrollingTest.verify_eroll(TC001EnrollingTest.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_eroll -->
  <testcase classname="testCases.TC001Enrolling" name="verify_eroll" time="1.509">
    <failure type="java.lang.AssertionError" message="expected [test] but found [test1]">
      <![CDATA[java.lang.AssertionError: expected [test] but found [test1]
at testCases.TC001Enrolling.verify_eroll(TC001Enrolling.java:25)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verify_eroll -->
</testsuite> <!-- Test(failed) -->
